version: "3.3"

networks:
  # Note there are two bridge networks. One for Zeebe and one for IAM. Operate, Tasklist, and Optimize use both
  camunda-cloud: { }
  camunda-platform: { }

services:
########################################
# Camunda Service
########################################
  camunda-platform:
    build:
      context: https://github.com/camunda/docker-camunda-bpm-platform.git#next
      dockerfile: Dockerfile
      args:
        EE: 'false'
        DISTRO: tomcat
        VERSION: 7.16.0
        USER: <<creds>>
        PASSWORD: <<creds>>
    image: camunda-platform
    links:
      - camunda-postgres
    ports:
      - "8080:8080"
    volumes:
      - ./license.txt:/camunda/.camunda/license.txt
      - ./camunda-tomcat-docker/multi-schema-server.xml:/camunda/conf/server.xml
      - ./camunda-tomcat-docker/bpm-platform-multi-schema-tenant.xml:/camunda/conf/bpm-platform.xml
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 1000M
        reservations:
          memory: 1000M
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/engine-rest/engine"]
      interval: 30s
      timeout: 10s
      retries: 5
    depends_on:
      - camunda-postgres
      - apacheds
    networks:
      - camunda-platform